# Generated by Django 2.1.7 on 2019-03-16 11:05

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(default='co-worker', max_length=300)),
                ('hire_date', models.DateTimeField(help_text='Please use the following format: <em>DD/MM/YYYY</em>.', verbose_name='Hire Date')),
                ('salary', models.IntegerField(default=0)),
                ('department', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='department.Department')),
            ],
        ),
    ]
