# Generated by Django 2.1.7 on 2019-03-26 07:12

from django.db import migrations, models
import workers.models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20190324_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=workers.models.workers_directory_path),
        ),
    ]
